/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.pantalla_principal;

import app.login.login;
import javax.swing.JOptionPane;

/**
 *
 * @author guill
 */
public class pantalla_principal extends javax.swing.JFrame {

    /**
     * Creates new form pantalla_principal
     */
    public pantalla_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan_menu = new javax.swing.JPanel();
        btn_inicio = new javax.swing.JButton();
        btn_alta_cliente = new javax.swing.JButton();
        btn_catalogo_cliente = new javax.swing.JButton();
        btn_reporte_general = new javax.swing.JButton();
        btn_reporte_acumulado = new javax.swing.JButton();
        btn_configuracion = new javax.swing.JButton();
        btn_cerrar_sesion = new javax.swing.JButton();
        imagen_gym = new javax.swing.JLabel();
        pan_bienvenida = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        pan_menu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menú", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 24), new java.awt.Color(102, 102, 102))); // NOI18N

        btn_inicio.setText("Inicio");

        btn_alta_cliente.setText("Alta de cliente");

        btn_catalogo_cliente.setText("Catálogo de cliente");

        btn_reporte_general.setText("Reporte general");

        btn_reporte_acumulado.setText("Reporte acumulado");

        btn_configuracion.setText("Configuración");

        btn_cerrar_sesion.setText("Cerrar sesión");
        btn_cerrar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrar_sesionActionPerformed(evt);
            }
        });

        imagen_gym.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/resources/images/imagenGym.jpg"))); // NOI18N

        javax.swing.GroupLayout pan_menuLayout = new javax.swing.GroupLayout(pan_menu);
        pan_menu.setLayout(pan_menuLayout);
        pan_menuLayout.setHorizontalGroup(
            pan_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_alta_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_catalogo_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_reporte_acumulado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_reporte_general, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_configuracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_cerrar_sesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pan_menuLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(imagen_gym)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        pan_menuLayout.setVerticalGroup(
            pan_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_inicio)
                .addGap(18, 18, 18)
                .addComponent(btn_alta_cliente)
                .addGap(18, 18, 18)
                .addComponent(btn_catalogo_cliente)
                .addGap(18, 18, 18)
                .addComponent(btn_reporte_acumulado)
                .addGap(18, 18, 18)
                .addComponent(btn_reporte_general)
                .addGap(18, 18, 18)
                .addComponent(btn_configuracion)
                .addGap(18, 18, 18)
                .addComponent(btn_cerrar_sesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(imagen_gym)
                .addGap(59, 59, 59))
        );

        pan_bienvenida.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bienvenido", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 24))); // NOI18N

        jLabel1.setText("Lealtad de cliente");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Con este programa se \npodrá dar de alta clientes para \ndarle seguimiento en el programa de lea");
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout pan_bienvenidaLayout = new javax.swing.GroupLayout(pan_bienvenida);
        pan_bienvenida.setLayout(pan_bienvenidaLayout);
        pan_bienvenidaLayout.setHorizontalGroup(
            pan_bienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_bienvenidaLayout.createSequentialGroup()
                .addGroup(pan_bienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_bienvenidaLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel1))
                    .addGroup(pan_bienvenidaLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        pan_bienvenidaLayout.setVerticalGroup(
            pan_bienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_bienvenidaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pan_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pan_bienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pan_bienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerrar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrar_sesionActionPerformed
        //int dialogButton = 0;
        int dialogResult = JOptionPane.showConfirmDialog (null, "¿Está seguro que desea salir?");
        if(dialogResult == JOptionPane.YES_OPTION){
            login l = new login();
            this.dispose();
            l.show();
        }
    }//GEN-LAST:event_btn_cerrar_sesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantalla_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantalla_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantalla_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantalla_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantalla_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alta_cliente;
    private javax.swing.JButton btn_catalogo_cliente;
    private javax.swing.JButton btn_cerrar_sesion;
    private javax.swing.JButton btn_configuracion;
    private javax.swing.JButton btn_inicio;
    private javax.swing.JButton btn_reporte_acumulado;
    private javax.swing.JButton btn_reporte_general;
    private javax.swing.JLabel imagen_gym;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel pan_bienvenida;
    private javax.swing.JPanel pan_menu;
    // End of variables declaration//GEN-END:variables
}
